apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app-chart.fullname" . }}
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "my-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my-app-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "my-app-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.service.ports }}
            - name: http
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          env: # Biến môi trường bổ sung
            {{- toYaml .Values.extraEnv | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- $root := . }} # Gán root context
            {{- if .Values.configMaps }}
              {{- range $cmKey, $configMap := .Values.configMaps }}
                {{- if $configMap.enabled }}
                  {{- range $mountKey, $mount := $configMap.mounts }}
            - name: {{ include "my-app-chart.fullname" $root }}-{{ $cmKey }}-volume
              mountPath: {{ $mount.mountPath }}
              subPath: {{ $mount.subPath }}
              readOnly: true
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
            # --- Cấu hình mount các Persistent Volume Claims ---
            {{- if .Values.persistentVolumes }}
              {{- range $pvcKey, $pvc := .Values.persistentVolumes }}
                {{- if $pvc.enabled }}
            - name: {{ include "my-app-chart.fullname" $root }}-{{ $pvcKey }}-volume # Tên volumeMount tương ứng với tên Volume
              mountPath: {{ $pvc.mountPath }}
              {{- if $pvc.subPath }}
              subPath: {{ $pvc.subPath }}
              {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
      volumes:
        {{- $root := . }} # Gán root context
        {{- if .Values.configMaps }}
          {{- range $cmKey, $configMap := .Values.configMaps }}
            {{- if $configMap.enabled }}
        - name: {{ include "my-app-chart.fullname" $root }}-{{ $cmKey }}-volume
          configMap:
            name: {{ include "my-app-chart.fullname" $root }}-{{ $configMap.name }}
            {{- end }}
          {{- end }}
        {{- end }}
        # --- Định nghĩa các Volume cho Persistent Volume Claims ---
        {{- if .Values.persistentVolumes }}
          {{- range $pvcKey, $pvc := .Values.persistentVolumes }}
            {{- if $pvc.enabled }}
        - name: {{ include "my-app-chart.fullname" $root }}-{{ $pvcKey }}-volume # Tên Volume tương ứng với tên PVC
          persistentVolumeClaim:
            claimName: {{ include "my-app-chart.fullname" $root }}-{{ $pvcKey }}-pvc # Liên kết với tên PVC đã tạo
            {{- end }}
          {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}