{{- range $key, $persistentVolumes := .Values.persistentVolumes }}
{{- if $persistentVolumes.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-app-chart.fullname" $ }}-{{ $key }}-pvc # Tên PVC sẽ là <release-name>-<chart-name>-<key-tu-values>-pvc
  labels:
    {{- include "my-app-chart.labels" $ | nindent 4 }}
spec:
  accessModes:
    {{- toYaml $persistentVolumes.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $persistentVolumes.size }}
  {{- if $persistentVolumes.storageClassName }}
  storageClassName: {{ $persistentVolumes.storageClassName }}
  {{- end }}
---
{{- end }}
{{- end }}